id: P007003
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ75
  title: རྒྱུད་ཀྱི་རྒྱལ་པོ་དཔལ་དུས་ཀྱི་འཁོར་ལོ།
  author: ''
  volumes:
    8f1eb3eba49e438e9c2d1ea13c2b53d1:
      image_group_id: I1PD105176
      title: Volume 1 of dus 'khor rgyud/
      volume_number: 1
      total_pages: 370
      base_file: v001.txt
ebook_metadata:
  title: རྒྱུད་ཀྱི་རྒྱལ་པོ་དཔལ་དུས་ཀྱི་འཁོར་ལོ།
  author: ''
  sku: P007003
  cover: cover.jpg
  layers:
  - pagination
