id: P007003
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ75
  title: རྒྱུད་ཀྱི་རྒྱལ་པོ་དཔལ་དུས་ཀྱི་འཁོར་ལོ།
  author: ''
  volumes:
    6af1998fc176423caa02f4aeffeddf01:
      image_group_id: I1PD105176
      title: ''
      volume_number: 1
      total_pages: 370
ebook_metadata:
  title: རྒྱུད་ཀྱི་རྒྱལ་པོ་དཔལ་དུས་ཀྱི་འཁོར་ལོ།
  author: ''
  sku: P007003
  cover: cover.jpg
  layers:
  - pagination
